# Dockerfile para el front
FROM python:3.9-slim

WORKDIR /app

# Copiar requirements.txt e instalar dependencias
COPY mi_proyecto_flask/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copiar la aplicación
COPY . .

# Exponer puerto 8000 para el front
EXPOSE 5000

CMD ["python3", "app.py"]
