FROM python:3.9-slim

WORKDIR /app

COPY mi_proyecto_flask/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY mi_proyecto_flask /app


EXPOSE 3000

CMD ["python3", "app.py", "--host", "0.0.0.0", "--port", "8000"]
